apiVersion: v1
kind: Secret
metadata:
  name: utak-spark-02-secret
  labels:
    app.kubernetes.io/name: spark
    app.kubernetes.io/instance: utak-spark-02
    app.kubernetes.io/managed-by: Tiller
type: Opaque
data:
